version: '2.1'
services:
  ktor-graphql-template:
    container_name: ktor-graphql-template
    image: ktor-graphql-api:SNAPSHOT
    build:
      context: ktor-graphql-template
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8080:8080
#   environment:
#      JAVA_ENV: local
#      PORT: 8082
#      DB_URL: jdbc:postgresql://10.128.15.6:5432/template_db
#      APP_SQL_USER: example_user
#      APP_SQL_PASSWORD: pass
#      FLYWAY_SQL_USER: flyway
#      FLYWAY_SQL_PASSWORD: pass
    networks:
      ktor:
        ipv4_address: 10.128.15.5

  postgres:
    container_name: example-postgres
    image: postgres
    build:
      context: postgres
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U template_db"]
      interval: 10s
      timeout: 30s
      retries: 3
    networks:
      ktor:
        ipv4_address: 10.128.15.6

networks:
  ktor:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.128.15.0/24
